### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by tmcarr** [7kfpun/atom-finance#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [finance](https://github.com/7kfpun/atom-finance) package, v0.7.0
### Stack Trace

Uncaught SyntaxError: Unexpected token <

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Ftcarr%2Fworkspace%2Fci-job-configs%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Ftcarr%2Fworkspace%2Fci-job-configs%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2Fkl%2Fpqcxhzhs6nlg6tg81jc9yw6c0000gn%2FT%2F%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0x0%22%2C%22HOME%22%3A%22%2FUsers%2Ftcarr%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.LR2O6K0A5W%2FRender%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.UMWSAq7nzM%2FListeners%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22tcarr%22%2C%22DISPLAY%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.rGoUrMazQt%2Forg.macosforge.xquartz%3A0%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.58272%22%2C%22USER%22%3A%22tcarr%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Ftcarr%2F.atom%22%7D%2C%22appVersion%22%3A%221.7.3%22%2C%22atomHome%22%3A%22%2FUsers%2Ftcarr%2F.atom%22%2C%22shellLoadTime%22%3A909%7D:1

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/tcarr/.atom/packages/finance/lib/yahoo_finance.coffee:14:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "task-list",
      "vim-mode",
      "language-todo",
      "language-gfm",
      "antialiased"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "finance": {
    "display": "left",
    "refresh": 120,
    "scroll": "fixed",
    "separator": "|",
    "watchlist": "TWTR"
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
api-docs, v0.0.4
atom-clock, v0.0.8
atom-django, v0.3.2
atom-jinja2, v0.5.0
atometer, v0.1.0
autocomplete-go, v1.1.0
autocomplete-json, v1.10.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.3
builder-go, v1.0.0
color-picker, v2.1.1
default-language, v0.3.0
environment, v1.2.0
file-icons, v1.7.11
file-watcher, v0.4.0
filesize, v0.4.2
finance, v0.7.0
fonts, v1.2.0
formatter-clang-format, v0.1.2
git-hide, v0.1.2
git-log, v0.4.1
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
indent-guide-improved, v1.4.8
language-ansible, v0.1.6
language-apache, v1.5.0
language-autotools, v2.0.1
language-chef, v0.9.0
language-conky, v0.2.0
language-crontab, v0.2.1
language-diff, v0.4.0
language-docker, v1.1.6
language-dotfiles, v0.3.0
language-dots, v0.0.4
language-erlang, v3.0.0
language-groovy, v0.6.0
language-ino, v0.1.0
language-javascript-jsx, v0.3.7
language-m68k, v1.1.0
language-mako, v0.6.0
language-markdown, v0.13.0
language-mongodb, v0.3.1
language-nginx, v0.6.1
language-particle, v0.3.4
language-protobuf, v0.5.0
language-puppet, v0.19.1
language-restructuredtext, v0.13.0
language-routeros-script, v0.2.0
language-rust, v0.4.6
language-scala, v1.1.6
language-supercollider, v0.2.0
language-systemd, v0.1.1
language-tmux, v0.4.0
language-todo-extra-words, v0.2.0
language-todotxt, v0.6.1
language-vb, v0.1.0-pre1
language-x86, v1.0.1
less-than-slash, v0.13.0
linter, v1.11.4
linter-checkbashisms, v0.1.5
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
navigator-godef, v1.0.3
project-manager, v2.9.7
rst-preview, v1.3.1
rst-preview-pandoc, v0.1.12
ssh-config, v0.10.1
svn, v0.0.10
symbols-tree-view, v0.12.0
sync-settings, v0.7.2
tasks, v2.6.0
tester-go, v1.0.4
text-manipulation, v0.6.0
useful-context-menu, v0.6.0
yaml-path, v0.1.0

# Dev
No dev packages
```

**Comment by 7kfpun** [comment]
Thanks @tmcarr!
Added try/catch, it should be fixed.
