### ISSUE TITLE
Uncaught TypeError: Failed to execute 'item' on 'HTMLCollection': 1 argument required, but only 0...

### ISSUE THREAD

**Issue by sriharshakappala** [7kfpun/atom-finance#3]
1. Open Atom editor
2. Toggle Finance plugin

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [finance](https://github.com/7kfpun/atom-finance) package 0.9.0

### Stack Trace

Uncaught TypeError: Failed to execute 'item' on 'HTMLCollection': 1 argument required, but only 0 present.

```
At /home/harsha/.atom/packages/finance/lib/finance-view.coffee:103

TypeError: Failed to execute 'item' on 'HTMLCollection': 1 argument required, but only 0 present.
    at HTMLElement.FinanceView.hasParent (/packages/finance/lib/finance-view.coffee:103:14)
    at HTMLElement.FinanceView.toggle (/packages/finance/lib/finance-view.coffee:97:9)
    at /packages/finance/lib/finance-view.coffee:11:8)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:21.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:18.2.0 intentions:highlight (input.hidden-input)
     -0:18.1.0 command-palette:toggle (input.hidden-input)
     -0:14 core:confirm (input.hidden-input)
     -0:14 finance:toggle (input.hidden-input)
     -0:07.2.0 command-palette:toggle (input.hidden-input)
     -0:05.5.0 core:move-down (input.hidden-input)
     -0:05.2.0 core:confirm (input.hidden-input)
     -0:05.2.0 finance:refresh (input.hidden-input)
     -0:04.0 intentions:highlight (input.hidden-input)
     -0:03.9.0 command-palette:toggle (input.hidden-input)
     -0:01.9.0 core:confirm (input.hidden-input)
     -0:01.9.0 finance:toggle (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.5 
atom-erb 0.2.0 
atom-ide-ui 0.5.2 
atom-music 0.7.0 
atom-pair 2.0.13 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
change-case 0.6.5 
editorconfig 2.2.2 
file-icons 2.1.13 
finance 0.9.0 
git-blame 1.3.1 
git-control 0.9.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
goto-definition 1.3.4 
imdone-atom 2.2.7 
intentions 1.1.5 
linter 2.2.0 
linter-erb 1.1.0 
linter-rubocop 2.2.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
nuclide 0.262.0 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
qolor 0.4.2 
rails-snippets 2.16.0 
remote-edit 1.9.0 
spotify-remote 1.0.2 
tasks 2.6.7 
tool-bar 1.1.0 
tool-bar-basic 2.0.1 
tool-bar-main 0.0.10 
```

**Comment by 7kfpun** [comment]
I think it was a bug from Yahoo and they already fixed. Please confirm me whether it works, thanks.
<img width="956" alt="screen shot 2017-10-29 at 11 34 12 am" src="https://user-images.githubusercontent.com/2672802/32140507-d1d82240-bc9d-11e7-9c91-ae47bbfaf1b1.png">

**Comment by sriharshakappala** [comment]
@7kfpun The issue still exists.
